// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuEtoxRPV5xDESNAFJnsJ7UDryrPXvp7E',
    appId: '1:967996568401:web:f1755924a60c9067725970',
    messagingSenderId: '967996568401',
    projectId: 'scarpetta-bb13b',
    authDomain: 'scarpetta-bb13b.firebaseapp.com',
    storageBucket: 'scarpetta-bb13b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXYI-NTqAp8cGgPf3OTwuvEYvYZIqNCsU',
    appId: '1:967996568401:android:82afb0d24c1e1357725970',
    messagingSenderId: '967996568401',
    projectId: 'scarpetta-bb13b',
    storageBucket: 'scarpetta-bb13b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDD56rMwB06nEm0AX8gH3BvhcCTL_y4DTI',
    appId: '1:967996568401:ios:eda7a2a1df62eaed725970',
    messagingSenderId: '967996568401',
    projectId: 'scarpetta-bb13b',
    storageBucket: 'scarpetta-bb13b.appspot.com',
    iosBundleId: 'com.example.scarpetta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDD56rMwB06nEm0AX8gH3BvhcCTL_y4DTI',
    appId: '1:967996568401:ios:eda7a2a1df62eaed725970',
    messagingSenderId: '967996568401',
    projectId: 'scarpetta-bb13b',
    storageBucket: 'scarpetta-bb13b.appspot.com',
    iosBundleId: 'com.example.scarpetta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuEtoxRPV5xDESNAFJnsJ7UDryrPXvp7E',
    appId: '1:967996568401:web:bc8fe7a1a74c3d8f725970',
    messagingSenderId: '967996568401',
    projectId: 'scarpetta-bb13b',
    authDomain: 'scarpetta-bb13b.firebaseapp.com',
    storageBucket: 'scarpetta-bb13b.appspot.com',
  );

}